trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'tre-sc-ai-tech-lab'
  staticWebAppName: 'tre-swa-lapoc'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
      displayName: 'Install Node.js'

  - script: |
      cd frontend
      npm ci
      npm run build
    displayName: 'Build frontend'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: '$(swa_deployment_token)'
      app_location: 'frontend'
      output_location: 'dist'
      skip_app_build: true
      skip_api_build: true
